# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

apiVersion: v2
name: crowsi
description: a honeypot platform for edge devices

type: application

# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

home: www.crowsi.com

# dependencies:
#   - name: traefik
#     version: 25.0.0
#     repository: https://traefik.github.io/charts
  