# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

apiVersion: v2
name: crowsi
description: A Helm chart to deploy crowsi, a honeypot solution for edge devices.

type: application


version: 1.0.0

acmeServer: https://acme-v02.api.letsencrypt.org/directory



