# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

#This file specifies the cert-manager resource that act as certificate issuer. Via this resource the let's encrypt certificate used for TLS will be requested
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: letsencrypthttpchallenge #name of the resource
spec:
 acme:
   email: {{ .Values.mail }} #mail adress used to issue server certificate from let's encrypt
   server: {{ .Values.acmeServer }}   #server address being used to retrieve trusted let's encrypt certificates

   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: tls-issuer-account-key
   solvers:
     - http01:  #challenge type used for the retrieval of tls certificates. Cluster needs to be reachable via http. Redirecting to 443 should be possible.
         # The ingressClass used to create the necessary ingress routes
         ingress:
          ingressClassName: traefik
          serviceType: ClusterIP
          ingressTemplate:
            metadata:
              annotations:
                traefik.ingress.kubernetes.io/router.tls.options: default-certmanoptions@kubernetescrd
