# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

#This file specifies the default API that is used when no other suitable path and with that deployed decoy is requested

apiVersion: apps/v1
kind: Deployment
metadata:
  name: defaultapi-deployment
  labels:
    app: defaultapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defaultapi
  template:
    metadata:
      labels:
        app: defaultapi
    spec:
      containers:
      - name: defaultapi
        image: crowsi/httpcatcherdecoy:1.1.0  
        ports:
        - containerPort: 8000
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: "RuntimeDefault"

---

apiVersion: v1
kind: Service
metadata:
  name: defaultapi-service
spec:
  selector:
    app: defaultapi
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000


---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limit-defaultapi-communication
spec:
  podSelector:
    matchLabels:
        app: defaultapi
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: traefik
  - ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: traefik
    ports:
    - protocol: TCP
      port: 8000