# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---

#Ingress route for the defaultAPI service
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: defaultapiingressroute
  namespace: default

spec:
  entryPoints:
    - websecure

  routes:
  - match: PathPrefix(`/`)
    priority: 1
    kind: Rule
    services:
    - name: defaultapi-service
      port: 8000