annotations:
  artifacthub.io/changes: "- \"feat(podtemplate): set GOMEMLIMIT, GOMAXPROCS when
    limits are defined\"\n- \"feat: ✨ fail gracefully when required port number is
    not set\"\n- \"feat!: :boom: initial support of Traefik Proxy v3\"\n- \"docs:
    \U0001F4DA️ improve EXAMPLES on acme resolver\"\n- \"chore(release): \U0001F680
    publish v28 rc1\"\n"
apiVersion: v2
appVersion: v3.0.0-rc5
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.22.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: charlie.haley@traefik.io
  name: charlie-haley
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 28.0.0-rc.1
