# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


#This secret is a CA file used for client authentication.
#Any client which provides a client certificate which can be valid against this ca file is granted whith access to the resources behind traefik
apiVersion: v1
kind: Secret
metadata:
  name: client-auth-ca-cert #reference which is used in the traefik values specification
type: Opaque
data:
  #key "ca.crt" cannot be changed since traefik looks for a secret that is either called ca.crt or tls.crt
  #needs to be base64 encoded string
  #base64 encoding can be done with 
  #cat ca.crt | base64
  ca.crt: {{ .Values.cacrt }}
