# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

#This file specifies defines the allowed network communication within the cluster

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik
spec:
  podSelector:
    matchLabels:
      app: traefik  # Label for the Traefik-Container
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
  
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: disallow-communication
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: traefik
  - ports:
    - protocol: TCP
      port: 8000
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: traefik
    ports:
    - protocol: TCP
      port: 8000