# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: passtlsclientcert
spec:
  passTLSClientCert:
    pem: false
    info:
      serialNumber: true
      subject:
        organization: true
        serialNumber: true