---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: passtlsclientcert
spec:
  passTLSClientCert:
    pem: false
    info:
      serialNumber: true
      subject:
        organization: true
        serialNumber: true